import {$,$$,escapeHTML,mean,download,toast,formatDate} from './utils.js';
import {load,get,save,update,replace,reset} from './storage.js';
import {trainingView,bindTraining} from './training.js';
import {due,scoreReview,action} from './reviews.js';
import {configured,watchAuthState,signInWithGoogle,signOutGoogle,loadCloudState,saveCloudState,currentFirebaseUser} from './firebase.js';

const data = {};
const challengeState = { step: 'choose', challenge: null, baseline: null, final: null };
const beginnerChallenges = [
  {id:'planets', title:'The eight planets in order', time:'8 minutes', method:'link method', material:['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune'], prompt:'Imagine a thermometer made of mercury falling in love with Venus, landing on Earth, and being painted red by Mars.'},
  {id:'uk-capitals', title:'UK countries and capitals', time:'9 minutes', method:'story method', material:['England — London','Scotland — Edinburgh','Wales — Cardiff','Northern Ireland — Belfast'], prompt:'Picture a lion in London, a thistle at Edinburgh Castle, a red dragon driving a card in Cardiff, and a ringing bell in Belfast.'},
  {id:'metric', title:'Useful metric conversions', time:'8 minutes', method:'image association', material:['1 kilometre = 1000 metres','1 metre = 100 centimetres','1 kilogram = 1000 grams','1 litre = 1000 millilitres','0°C = water freezes'], prompt:'Turn each number into a visible object: a thousand tiny metres marching, one metre ruler sprouting 100 centimetre ants, and frozen water at zero.'},
  {id:'prime-ministers', title:'A short prime-minister sequence', time:'10 minutes', method:'ordered story', material:['Churchill','Attlee','Churchill','Eden','Macmillan','Douglas-Home'], prompt:'Make each person do an impossible action to the next: Churchill hands a cigar to Attlee, then returns through a giant door into Eden.'},
  {id:'shopping', title:'A practical shopping list', time:'7 minutes', method:'link method', material:['Bread','Milk','Bananas','Eggs','Tomatoes','Pasta','Soap','Tea'], prompt:'Make bread explode milk over bananas, bananas juggle eggs, eggs smash tomatoes, tomatoes dye pasta red, pasta ties up soap, soap slides into tea.'}
];
const handbookChapters = ['Observation and attention','Visualisation','Association','Exaggeration and absurdity','Linking method','Story method','Memory palace','Journey method','Peg systems','Major System','PAO','Name and face memory','Number memory','Dates','Vocabulary','Speeches','Spaced retrieval','Active recall','Error correction','Building automaticity','Choosing the correct technique'];

async function boot(){
  for (const n of ['belts','curriculum','starter-major-system','starter-symbols','example-palace','programme']) data[n]=await fetch(`data/${n}.json`).then(r=>r.json());
  load();
  await initialiseAuth();
  if(!get().majorSystem.length) update(s=>{s.majorSystem=data['starter-major-system'];s.symbols=data['starter-symbols'];s.palaces=[data['example-palace']]});
  applyTheme();
  route();
  window.addEventListener('hashchange',route);
  window.addEventListener('dojo:data',()=>{badges();queueCloudSave()});
}

function page(kicker,title,body,action=''){return `<section class="page-hero"><p class="eyebrow">${kicker}</p><h1>${title}</h1>${body}${action}</section>`}
function primaryAction(href,label){return `<a class="button primary-action" href="${href}">${label}</a>`}
function challengeComplete(){return get().firstSuccess?.completed}
function currentDay(){return Math.min(get().profile.currentDay,84)}
function todaySession(){return data.curriculum[currentDay()-1]}

function dashboard(){
  const s=get(), today=todaySession(), reviews=due(), completed=challengeComplete(), avg=mean(s.results.map(x=>x.accuracy));
  const actionHref = !completed ? '#learn' : reviews.length ? '#reviews' : '#train';
  const actionLabel = !completed ? 'Memorise something useful' : reviews.length ? 'Do due review' : `Continue Day ${currentDay()}`;
  return `${page('Today','What should I do now?',`<p class="lead">${completed?'Keep the skill alive with one useful retrieval practice.':'Start with a short success experience before exploring advanced tools.'}</p>`,primaryAction(actionHref,actionLabel))}
  <section class="next-step-panel"><div><p class="eyebrow">Recommended next action</p><h2>${!completed?'Complete your first memory success':reviews.length?'Retrieve before review':'Today’s lesson'}</h2><p>${!completed?'Choose a useful beginner challenge, try a no-pressure baseline, learn one method, and retest.':'Retrieval strengthens the route back to the memory. Looking again comes later.'}</p><dl class="answer-grid"><div><dt>Why?</dt><dd>${!completed?'To prove the method works with real recall.':'To keep memory access strong.'}</dd></div><div><dt>Time</dt><dd>${!completed?'7–10 minutes':`${today.timeLimitMinutes} minutes`}</dd></div><div><dt>After</dt><dd>${!completed?'You will get a first review time.':'A delayed review is scheduled.'}</dd></div></dl></div><a class="button" href="${actionHref}">${actionLabel}</a></section>
  <section class="quiet-grid"><article><h2>Current lesson</h2><p><strong>${escapeHTML(today.title)}</strong></p><p>${escapeHTML(today.goal)}</p></article><article><h2>Due review</h2><p>${reviews.length?`${reviews.length} item${reviews.length===1?'':'s'} due now`:'No reviews due right now.'}</p><a href="#reviews">Open review queue</a></article><article><h2>Progress, briefly</h2><p>${avg?`${avg}% average immediate recall across ${s.results.length} session${s.results.length===1?'':'s'}.`:'Your first score will appear after a recall test.'}</p></article></section>`;
}

function learn(){
  const done=challengeComplete();
  return `${page('Learn','Experience the method before the theory',`<p class="lead">Choose one useful challenge. We will test a baseline, teach one memory method interactively, retest without the source, then explain why it worked.</p>`,done?primaryAction('#guidance','Open Memory Handbook'):primaryAction('#learn','Choose a challenge'))}
  ${done?completedFirstSuccess():firstSuccessJourney()}
  <section class="section-block"><div class="section-heading"><p class="eyebrow">Courses</p><h2>Continue learning</h2></div><div class="quiet-grid"><a class="path-card" href="#train"><strong>Daily curriculum</strong><span>84 structured sessions</span></a><a class="path-card" href="#guidance"><strong>Memory Handbook</strong><span>Technique reference after practice</span></a><a class="path-card" href="#reviews"><strong>Review queue</strong><span>Spaced retrieval practice</span></a></div></section>`;
}
function firstSuccessJourney(){
  if(challengeState.step==='choose') return `<section class="journey-panel" id="first-success"><p class="eyebrow">First success</p><h2>Pick something useful to memorise</h2><p class="measure">No sign-in. No judgement. You will first try from memory, then learn the method and see what improves.</p><div class="challenge-grid">${beginnerChallenges.map(c=>`<button class="challenge-card" data-challenge="${c.id}"><strong>${escapeHTML(c.title)}</strong><span>${c.time} · ${escapeHTML(c.method)}</span></button>`).join('')}</div></section>`;
  const c=challengeState.challenge;
  if(challengeState.step==='baseline') return recallStep('Baseline attempt', 'Look once, then hide the source and recall what you can. This is not a test of you; it only shows the starting point.', c, 'Save baseline', 'baseline');
  if(challengeState.step==='teach') return `<section class="journey-panel"><p class="eyebrow">Learn by doing</p><h2>Make it concrete, active and strange</h2><ol class="method-steps"><li><strong>Concrete image:</strong> turn each item into something you can see.</li><li><strong>Exaggerate:</strong> make it too big, noisy, moving or emotional.</li><li><strong>Link:</strong> make each image interact with the next image.</li><li><strong>Retrieve:</strong> close the list and walk the story from the first image.</li></ol><div class="example-story"><p>${escapeHTML(c.prompt)}</p></div><button data-journey="practice">Practise the associations</button></section>`;
  if(challengeState.step==='practice') return `<section class="journey-panel"><p class="eyebrow">Practice</p><h2>Walk the story aloud or in your head</h2><div class="practice-strip">${c.material.map((x,i)=>`<span>${i+1}. ${escapeHTML(x)}</span>`).join('')}</div><p class="measure">Now close the source. Picture the first image causing the second, then the second causing the third. If an image is weak, make it larger, louder or stranger.</p><button data-journey="final">Hide source and retest</button></section>`;
  if(challengeState.step==='final') return recallStep('Retrieval test', 'The source is hidden. Recall the items in order using your image story.', c, 'Show my result', 'final');
  return successStep();
}
function recallStep(kicker, intro, c, button, mode){return `<section class="journey-panel"><p class="eyebrow">${kicker}</p><h2>${escapeHTML(c.title)}</h2><p class="measure">${intro}</p><details open><summary>Source material</summary><ol class="source-list">${c.material.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ol></details><button data-hide-source>Hide source</button><form class="recall-form" data-recall="${mode}"><label>Recall one item per line<textarea required autocomplete="off"></textarea></label><button>${button}</button></form></section>`}
function successStep(){const c=challengeState.challenge,b=challengeState.baseline||{accuracy:0,correct:0},f=challengeState.final||{accuracy:0,correct:0};const improvement=f.accuracy-b.accuracy;return `<section class="journey-panel success-panel"><p class="eyebrow">First success complete</p><h2>You remembered ${f.correct} of ${c.material.length}</h2><p class="result-number">${f.accuracy}%</p><p>${improvement>0?`That is ${improvement} percentage points better than your baseline.`:'You completed the full retrieval loop. Reinforcement comes from the review.'}</p><ul class="feedback-list"><li><strong>Technique:</strong> ${escapeHTML(c.method)}</li><li><strong>Why it worked:</strong> vivid interacting images give your brain a route back to the information.</li><li><strong>Reinforce:</strong> your first review is scheduled for about 20 minutes after a completed training set.</li></ul><button data-complete-first>Save this success</button></section>`}
function completedFirstSuccess(){const fs=get().firstSuccess;return `<section class="journey-panel success-panel"><p class="eyebrow">First success saved</p><h2>You have already proved the method works.</h2><p>Your first challenge was <strong>${escapeHTML(fs?.challengeTitle||'a beginner challenge')}</strong>. Choose a personal project next.</p><form id="projectForm"><label>My first useful memory project<select name="project"><option>Birthdays</option><option>Important telephone numbers</option><option>Shopping lists</option><option>Names</option><option>Speech points</option><option>Vocabulary</option><option>Dates</option><option>Study material</option><option>A master passphrase practice plan, stored outside this app</option></select></label><small>Do not store real passwords here. Use a reputable password manager for passwords.</small><button>Save project</button></form></section>`}

function library(){return `${page('Library','Keep tools out of the way until they are useful',`<p class="lead">Your projects and advanced memory systems live here. Start simple; open the athlete tools when the information calls for them.</p>`,primaryAction('#palaces','Create or edit a palace'))}<section class="quiet-grid"><a class="path-card" href="#palaces"><strong>Memory palaces</strong><span>${get().palaces.length||1} route started</span></a><a class="path-card" href="#major"><strong>Major System 00–99</strong><span>Number-image library</span></a><a class="path-card" href="#pao"><strong>PAO system</strong><span>Advanced number/card encoding</span></a><a class="path-card" href="#symbols"><strong>Symbol bank</strong><span>Reusable abstract images</span></a><a class="path-card" href="#names"><strong>Name images</strong><span>People and vocabulary hooks</span></a><a class="path-card" href="#contract"><strong>Training contract</strong><span>Your personal reason to train</span></a></section>`}
function progress(){const r=get().results;return `${page('Progress','What is improving?',`<p class="lead">Analytics are here when you need them, away from the main learning task.</p>`,primaryAction('#reviews','Review due material'))}<div class="grid"><div class="card metric"><span>Immediate</span><strong>${mean(r.map(x=>x.accuracy))}%</strong></div><div class="card metric"><span>Delayed</span><strong>${mean(get().reviews.filter(x=>x.reviewScore!=null).map(x=>x.reviewScore))}%</strong></div><div class="card metric"><span>Completed sessions</span><strong>${r.length}</strong></div></div><section class="card"><h2>Recent recall</h2><div class="chart" aria-label="Recent accuracy chart">${r.slice(-14).map(x=>`<div class="bar" style="height:${Math.max(2,x.accuracy)}%"><span>${x.accuracy}</span></div>`).join('')||'<p class="empty">Complete your first retrieval test to see progress.</p>'}</div><p>${insight()}</p></section><section class="quiet-grid"><a class="path-card" href="#belts"><strong>Belts and examinations</strong><span>Progression when ready</span></a><a class="path-card" href="#reviews"><strong>Review queue</strong><span>${due().length} due now</span></a></section>`}
function reviewView(){const items=get().reviews.filter(r=>r.status==='active');return page('Reviews','Retrieve before you reread',`<p class="lead">Poor recall shortens the interval; strong recall advances it.</p>`,items.length?primaryAction('#reviews','Start with the first due review'):'') + (items.length?items.map(r=>`<article class="card"><h3>${escapeHTML(r.title)}</h3><p>${r.nextReviewAt<=Date.now()?'<strong class="success">Due now</strong>':`Due ${formatDate(r.nextReviewAt)}`} · strength: ${r.strength}</p><details><summary>Start review</summary><p>Recall the set without looking. Then reveal and score honestly.</p><div class="material"><ol>${r.material.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ol></div><label>Recall percentage <input type="number" min="0" max="100" value="80" data-review-score="${r.id}"></label><button data-score="${r.id}">Save score</button></details><div class="actions"><button class="secondary" data-review="snooze:${r.id}">Snooze 1 day</button><button class="secondary" data-review="retire:${r.id}">Retire</button><button class="secondary" data-review="restart:${r.id}">Restart</button></div></article>`).join(''):'<div class="empty-state"><h2>No reviews due</h2><p>Complete a training session or first-success challenge to schedule future retrieval.</p><a class="button" href="#learn">Learn something useful</a></div>')}

function strongWeak(best){const by={};get().results.forEach(r=>(by[r.technique]??=[]).push(r.accuracy));const a=Object.entries(by).map(([k,v])=>[k,mean(v)]).sort((a,b)=>b[1]-a[1]);return a.length?(best?a[0]:a.at(-1))[0]:'Complete a session to discover this'}
function insight(){const s=get(),a=mean(s.results.map(x=>x.accuracy)),d=mean(s.reviews.filter(x=>x.reviewScore!=null).map(x=>x.reviewScore));if(!s.results.length)return 'Your first scored retrieval will establish a baseline.';if(d&&a-d>15)return 'Your images are memorable immediately but weaken during delayed recall.';if(s.results.reduce((n,x)=>n+x.orderErrors,0)>s.results.reduce((n,x)=>n+x.omitted,0))return 'Order errors are more common than omissions. Strengthen your route.';return 'Keep prioritising accurate recall and practical use over streaks.'}
function palaces(){return page('Library','Memory palaces',`<p class="lead">A good locus is fixed, distinct, easy to visualise, naturally ordered and large enough for an exaggerated image.</p>`,primaryAction('#library','Back to Library'))+`<button id="addPalace">Add palace</button>${get().palaces.map((p,pi)=>`<article class="card"><h2>${escapeHTML(p.name)}</h2><p>${escapeHTML(p.routeDescription||'')}</p><div class="route">${p.locations.map((l,i)=>`<div class="locus"><input aria-label="Location ${i+1}" value="${escapeHTML(l.name)}" data-locus="${pi}:${i}"><button class="secondary" data-del-locus="${pi}:${i}" aria-label="Delete location">×</button></div>`).join('')}</div><div class="actions"><button data-add-locus="${pi}">Add location</button><button class="secondary" data-reverse="${pi}">Practise backwards</button><button class="secondary" data-duplicate="${pi}">Duplicate</button><button class="secondary" data-export-palace="${pi}">Export</button></div></article>`).join('')}`}
function major(){return page('Library','Major System 00–99',`<p class="lead">Use this when ordinary numbers need reliable images. Vowels and h, w, y carry no value.</p>`,primaryAction('#library','Back to Library'))+`<p>0 s/z · 1 t/d · 2 n · 3 m · 4 r · 5 l · 6 j/sh/ch · 7 k/g · 8 f/v · 9 p/b.</p><div class="actions"><button id="majorTest">Timed mixed test</button><button class="secondary" id="majorCsv">Export CSV</button></div><div class="major-grid">${get().majorSystem.map((x,i)=>`<label class="major-cell"><strong>${x.number}</strong><small>${x.sounds}</small><input aria-label="Image for ${x.number}" value="${escapeHTML(x.userImage||x.defaultImage)}" data-major="${i}"></label>`).join('')}</div>`}
function genericBuilder(type,title,fields,guidance=''){const items=get()[type];return page('Library',title,`<p class="lead">${guidance||'Build a personal memory library gradually as real needs appear.'}</p>`,primaryAction('#library','Back to Library'))+`<form id="genericForm" data-type="${type}" class="card">${fields.map(f=>`<label>${f}<input name="${f}" required></label>`).join('')}<button>Add entry</button></form><div class="quiet-grid">${items.map((x,i)=>`<article class="card"><h3>${escapeHTML(x[fields[0]]||x.concept||'Entry')}</h3>${fields.slice(1).map(f=>`<p><strong>${f}:</strong> ${escapeHTML(x[f]||'—')}</p>`).join('')}<button class="danger" data-delete-generic="${type}:${i}">Delete</button></article>`).join('')||'<div class="empty-state"><h2>No entries yet</h2><p>Add one useful item when you need it.</p></div>'}</div>`}
function belts(){const completed=get().results.length;return page('Progress','Belts and examinations',`<p class="lead">Use exams after you have experienced real recall improvement.</p>`,primaryAction('#progress','Back to Progress'))+data.belts.map((b,i)=>`<article class="card belt" style="--belt:${b.color}"><p class="eyebrow">${b.badge}</p><h2>${b.name}: ${b.subtitle}</h2><p>${b.purpose}</p><details><summary>Examination and eligibility</summary><p>${b.exam.brief}</p><ul>${b.exam.checklist.map(x=>`<li>${x}</li>`).join('')}</ul><p><strong>Unlock:</strong> ${b.unlock}</p><button data-exam="${b.id}" ${completed<(i+1)*3?'disabled':''}>Take eligibility check</button></details></article>`).join('')}
function guidance(){return page('Handbook','Memory Handbook',`<p class="lead">Theory lives here, after practice. Each chapter explains what to use, when not to use it, mistakes and a short exercise.</p>`,primaryAction('#learn','Back to Learn'))+`<div class="handbook-grid">${handbookChapters.map(ch=>`<article class="card handbook-card"><h2>${escapeHTML(ch)}</h2><p><strong>What it is:</strong> A practical way to make information more noticeable, structured and retrievable.</p><p><strong>Good for:</strong> Useful facts, sequences, names, numbers or study material when accuracy matters.</p><p><strong>When not to use it:</strong> Safety-critical data or real passwords that belong in secure systems.</p><ol><li>Notice the exact information.</li><li>Make a concrete image or structure.</li><li>Force interaction, movement or location.</li><li>Retrieve without looking.</li><li>Repair weak points.</li></ol><p><strong>Practice:</strong> Try one tiny example, then open a guided challenge.</p><a href="#learn">Guided challenge</a></article>`).join('')}</div>`}
function contract(){const c=get().contract,fs=['Why I want a trained memory','What I want to remember','Daily minimum','Normal training time','Training location','What I will do after missing a day','My first mastery project','Start date','Signature or name'];return page('Profile','Personal training contract',`<p class="lead">Identity before streaks: I am training the skill of remembering.</p>`,primaryAction('#settings','Back to settings'))+`<form id="contractForm" class="card">${fs.map(f=>`<label>${f}<input name="${f}" value="${escapeHTML(c[f]||'')}"></label>`).join('')}<button>Save contract</button></form>`}
function poster(){return `<article class="poster"><p class="eyebrow">Memory Mastery</p><h1>Daily Memory Warm-up</h1><h2>Recall before review</h2><ol><li>Close yesterday’s material.</li><li>Walk through yesterday’s palace.</li><li>Retrieve each image.</li><li>Mark it clear, vague or missing.</li><li>Repair only weak memories.</li><li>Then begin today’s training.</li></ol><h2>Why?</h2><ul><li>Retrieval strengthens the route back to a memory.</li><li>Effortful recall is more valuable than rereading.</li><li>Errors show which images need improvement.</li><li>Daily retrieval prevents rapid forgetting.</li></ul><blockquote>Notice. Encode. Place. Retrieve. Review.</blockquote><div class="actions no-print"><button onclick="print()">Print A4 poster</button></div></article>`}
function settings(){const p=get().profile;return page('Profile','Settings and data',`<p class="lead">Account, appearance, export and portability live here so learning screens can stay focused.</p>`,primaryAction('#dashboard','Back to Today'))+`<div class="card"><h2>Appearance</h2><label>Colour theme<select id="colorTheme"><option value="pastelPaper" ${p.colorTheme==='pastelPaper'?'selected':''}>Pastel paper</option><option value="pastelMint" ${p.colorTheme==='pastelMint'?'selected':''}>Pastel mint</option><option value="pastelLavender" ${p.colorTheme==='pastelLavender'?'selected':''}>Pastel lavender</option><option value="pastelSunset" ${p.colorTheme==='pastelSunset'?'selected':''}>Pastel sunset</option><option value="mono" ${p.colorTheme==='mono'?'selected':''}>High-contrast mono</option></select></label><label>Layout and look<select id="uiStyle"><option value="smartpaper" ${p.uiStyle==='smartpaper'?'selected':''}>Calm learning app</option><option value="focus" ${p.uiStyle==='focus'?'selected':''}>Focus mode</option><option value="compact" ${p.uiStyle==='compact'?'selected':''}>Compact</option><option value="minimal" ${p.uiStyle==='minimal'?'selected':''}>Minimal notebook</option></select></label><button id="themeSetting">Toggle light / dark</button></div><div class="card"><h2>Backup and portability</h2><p>Guest data stays in this browser. Export it before clearing site data or moving devices.</p><div class="actions"><button id="exportJson">Export JSON backup</button><button id="resultsCsv">Results CSV</button><button onclick="print()">Print progress</button><label class="button">Import JSON<input id="importJson" type="file" accept="application/json" hidden></label></div><button class="danger" id="reset">Erase local data</button></div><div class="card"><h2>Firebase sync</h2><p>${configured()?'Firebase configuration detected. Use Sign in to connect.':'Guest mode is active. Add your public Firebase configuration in <code>js/firebase.js</code>.'}</p></div><div class="quiet-grid"><a class="path-card" href="#contract"><strong>Training contract</strong><span>Edit your purpose</span></a><a class="path-card" href="#poster"><strong>Warm-up poster</strong><span>Print or display</span></a></div>`}

function route(){const hash=location.hash.slice(1)||'dashboard';const views={dashboard,learn,library,progress,train:()=>trainingView(data.curriculum),reviews:reviewView,palaces,major,pao:()=>genericBuilder('pao','Person–Action–Object',['Number or card','Person','Action','Object','Visual description','Familiarity','Distinctiveness'],'Choose instantly recognisable people, distinctive actions and concrete objects. Avoid duplicates.'),symbols:()=>genericBuilder('symbols','Symbol bank',['concept','image','meaning','exampleUse','category','strength']),names:()=>genericBuilder('nameImages','Name image builder',['Name','Sound-alike image','Meaning or origin','Distinctive image','Example association','Notes']),belts,guidance,contract,poster,settings};$('#main').innerHTML=(views[hash]||dashboard)();$$('nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${hash}`));bind(hash);badges();scrollTo(0,0)}
function bind(hash){
  if(hash==='train') bindTraining();
  $$('[data-challenge]').forEach(b=>b.onclick=()=>{challengeState.challenge=beginnerChallenges.find(c=>c.id===b.dataset.challenge);challengeState.step='baseline';route()});
  $$('[data-hide-source]').forEach(b=>b.onclick=()=>{b.previousElementSibling.open=false;b.remove()});
  $$('[data-journey]').forEach(b=>b.onclick=()=>{challengeState.step=b.dataset.journey;route()});
  $$('.recall-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const mode=f.dataset.recall,score=scoreLines(challengeState.challenge.material,$('textarea',f).value);challengeState[mode]=score;challengeState.step=mode==='baseline'?'teach':'success';route()});
  $('[data-complete-first]')?.addEventListener('click',()=>{const c=challengeState.challenge;update(s=>{s.firstSuccess={completed:true,challengeId:c.id,challengeTitle:c.title,baseline:challengeState.baseline,final:challengeState.final,completedAt:Date.now()}});toast('First success saved');route()});
  $('#projectForm')?.addEventListener('submit',e=>{e.preventDefault();const project=new FormData(e.target).get('project');update(s=>{s.firstSuccess=s.firstSuccess||{};s.firstSuccess.project=project});toast('Project saved')});
  $$('[data-score]').forEach(b=>b.onclick=()=>{scoreReview(b.dataset.score,+$(`[data-review-score="${b.dataset.score}"]`).value);route()});
  $$('[data-review]').forEach(b=>b.onclick=()=>{const[t,id]=b.dataset.review.split(':');action(id,t);route()});
  $('#addPalace')?.addEventListener('click',()=>{const name=prompt('Palace name');if(name)update(s=>s.palaces.push({name,routeDescription:'Describe the fixed route',locations:[]}));route()});
  $$('[data-add-locus]').forEach(b=>b.onclick=()=>{update(s=>s.palaces[+b.dataset.addLocus].locations.push({name:'New location',description:'',feature:''}));route()});
  $$('[data-del-locus]').forEach(b=>b.onclick=()=>{const[p,i]=b.dataset.delLocus.split(':').map(Number);if(confirm('Delete this location?'))update(s=>s.palaces[p].locations.splice(i,1));route()});
  $$('[data-locus]').forEach(el=>el.onchange=()=>{const[p,i]=el.dataset.locus.split(':').map(Number);update(s=>s.palaces[p].locations[i].name=el.value)});
  $$('[data-duplicate]').forEach(b=>b.onclick=()=>{update(s=>s.palaces.push({...structuredClone(s.palaces[+b.dataset.duplicate]),name:s.palaces[+b.dataset.duplicate].name+' copy'}));route()});
  $$('[data-reverse]').forEach(b=>b.onclick=()=>alert(get().palaces[+b.dataset.reverse].locations.map(x=>x.name).reverse().join(' → ')));
  $$('[data-export-palace]').forEach(b=>b.onclick=()=>download('palace.json',JSON.stringify(get().palaces[+b.dataset.exportPalace],null,2)));
  $$('[data-major]').forEach(el=>el.onchange=()=>update(s=>s.majorSystem[+el.dataset.major].userImage=el.value));
  $('#majorCsv')?.addEventListener('click',()=>download('major-system.csv','number,sounds,image\n'+get().majorSystem.map(x=>`${x.number},"${x.sounds}","${(x.userImage||x.defaultImage).replaceAll('"','""')}"`).join('\n'),'text/csv'));
  $('#majorTest')?.addEventListener('click',()=>{const x=get().majorSystem[Math.floor(Math.random()*100)],ans=prompt(`What image is ${x.number}?`);alert(normalAnswer(ans)===normalAnswer(x.userImage||x.defaultImage)?'Correct — automaticity strengthened.':`Repair it: ${x.userImage||x.defaultImage}`)});
  $('#genericForm')?.addEventListener('submit',e=>{e.preventDefault();const type=e.target.dataset.type,obj=Object.fromEntries(new FormData(e.target));update(s=>s[type].push(obj));route()});
  $$('[data-delete-generic]').forEach(b=>b.onclick=()=>{const[t,i]=b.dataset.deleteGeneric.split(':');if(confirm('Delete this entry?'))update(s=>s[t].splice(+i,1));route()});
  $('#contractForm')?.addEventListener('submit',e=>{e.preventDefault();save({contract:Object.fromEntries(new FormData(e.target))});toast('Contract saved')});
  $('#exportJson')?.addEventListener('click',()=>download(`memory-mastery-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(get(),null,2)));
  $('#resultsCsv')?.addEventListener('click',()=>download('daily-results.csv','day,date,type,technique,accuracy,correct,incorrect,omitted,orderErrors\n'+get().results.map(r=>[r.day,new Date(r.date).toISOString(),r.type,r.technique,r.accuracy,r.correct,r.incorrect,r.omitted,r.orderErrors].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv'));
  $('#importJson')?.addEventListener('change',async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(confirm('Import will replace current local data. Export a backup first. Continue?')){replace(d);route();toast('Backup imported')}}catch(err){alert(err.message)}});
  $('#reset')?.addEventListener('click',()=>{if(confirm('Permanently erase all local Memory Mastery data?')){reset();location.reload()}});
  $('#themeSetting')?.addEventListener('click',toggleTheme);
  $('#colorTheme')?.addEventListener('change',e=>{update(s=>s.profile.colorTheme=e.target.value);applyTheme();toast('Colour theme saved')});
  $('#uiStyle')?.addEventListener('change',e=>{update(s=>s.profile.uiStyle=e.target.value);applyTheme();toast('Layout saved')});
}
function scoreLines(expected, value){const entered=value.split('\n').map(normalAnswer).filter(Boolean),normalExpected=expected.map(normalAnswer);let correct=0,order=0;entered.forEach((v,i)=>{if(v===normalExpected[i])correct++;else if(normalExpected.includes(v))order++});return {correct,orderErrors:order,omitted:Math.max(0,expected.length-entered.length),accuracy:Math.round(correct/expected.length*100)}}
const normalAnswer=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9à-ÿ— -]/g,'').replace(/\s+/g,' ');
function badges(){const badge=$('#dueBadge');if(badge)badge.textContent=due().length}
function applyTheme(){const p=get().profile;document.body.classList.toggle('dark',p.theme==='dark');document.body.dataset.theme=p.colorTheme||'pastelPaper';document.body.dataset.ui=p.uiStyle||'smartpaper'}
function toggleTheme(){update(s=>s.profile.theme=s.profile.theme==='dark'?'light':'dark');applyTheme()}
let cloudSaveTimer;async function queueCloudSave(){if(!configured())return;const user=await currentFirebaseUser();if(!user)return;clearTimeout(cloudSaveTimer);cloudSaveTimer=setTimeout(()=>saveCloudState(user.uid,get()).catch(e=>console.warn('Cloud autosave failed',e)),900)}
async function initialiseAuth(){if(!configured())return;try{await watchAuthState(async user=>{const button=$('#authButton');if(button)button.textContent=user?'Sign out':'Sign in';if(!user)return;const cloud=await loadCloudState(user.uid);if(cloud&&confirm('Cloud Memory Mastery data was found. Load it on this device?')){replace(cloud);applyTheme();route();toast('Cloud data loaded')}else if(!cloud&&confirm('Save this guest data to your Firebase account now?')){await saveCloudState(user.uid,get());toast('Guest data migrated to Firebase')}})}catch(e){console.warn('Firebase auth unavailable',e)}}
async function handleAuth(){if(!configured())return alert('Add Firebase web configuration in js/firebase.js first. Guest mode is fully available.');try{const user=(await signInWithGoogle()).user;await saveCloudState(user.uid,get());toast(`Signed in as ${user.displayName||user.email||'Google user'}`)}catch(e){if(e.code==='auth/popup-closed-by-user')return;alert(`Google sign-in failed: ${e.message}`)}}
$('#theme').onclick=toggleTheme;
$('#authButton').onclick=async()=>{const signedIn=$('#authButton').textContent==='Sign out';if(signedIn){await signOutGoogle();toast('Signed out. Guest data remains on this device.');$('#authButton').textContent='Sign in'}else await handleAuth()};
$('#modal .close').onclick=()=>$('#modal').close();
boot().catch(e=>{$('#main').innerHTML=`<h1>Could not start</h1><p>${escapeHTML(e.message)}</p>`});
